---
abstract: 'use ArtNet with C<IO::Async>'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  IO::Async::Test: 0
  Test::More: 0.88
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Async-ArtNet
provides:
  Net::Async::ArtNet:
    file: lib/Net/Async/ArtNet.pm
    version: 0.01
requires:
  IO::Async::Loop: 0.59
  IO::Async::Socket: 0.59
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
